version: "3.7"

services:
  database:
    image: mysql:8.0
    platform: linux/amd64
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=codetest
      - MYSQL_USER=codetest
      - MYSQL_PASSWORD=swordfish
    ports:
      - "3306:3306"
    restart: always
      
  ingestion-container:
    image: ingestion-container
    build: images/ingestion-container
    command: ["./ingest_data.py"]
    volumes:
      - ./data:/data
      - ./logs:/logs
      
  summary-container:
    image: summary-container
    build: images/summary-container
    command: ["./summarize_data.py"]
    volumes:
      - ./data:/data
      - ./logs:/logs
  
  test-container:
    image: test-container
    build: images/test-container
    command: ["./test.py"]
    volumes:
      - ./data:/data